my_project/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from  django.conf.urls.static import static
from  django.conf  import  settings


import  captcha


urlpatterns = [
    path('admin/', admin.site.urls),
    path('operation/',include('operation.urls')),
    path('user/',include('user.urls')),
    path('',include('topic.urls')),
    re_path('^captcha/',include('captcha.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

operation/urls.py
from django.contrib import admin
from django.urls import path,include

from  .views import     Comment_View

app_name='operation'
urlpatterns = [
    path('comment/<int:content_id>',Comment_View.as_view(),name='comment_url'),

   ]

topic/urls.py
# -*- coding: utf-8 -*-

__author__ = 'Echor'

__date__ = 2018 / 9 / 11


from django.contrib import admin
from django.urls import path,include

from  .views import   Theme1_View,PubTopic_View,Index_View,default_index,Topic_Content_View


app_name='topic'
urlpatterns = [
    path('',default_index,name='index'),
    path('create/<str:username>/',PubTopic_View.as_view(),name='create_topic'),
    path('page/<int:page_id>/',Index_View.as_view(),name='page'),
    path('content/<int:content_id>/',Topic_Content_View.as_view(),name='topic_content'),
    path('theme/<int:theme_id>/',Theme1_View.as_view(),name='theme1'),
]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from  .views import Login_View,Register_Voew,logout_view,Info_Profile,Info_Reply

app_name='user'
urlpatterns = [
    path('login/',Login_View.as_view(),name='login'),
    path('register/',Register_Voew.as_view(),name='register'),
    path('logout/',logout_view,name='logout'),
    path('user/<str:username1>/',Info_Profile.as_view(),name='infoprofile'),
    path('reply/<str:username1>/',Info_Reply.as_view(),name='inforeply'),
]

topic/models.py
from django.db import models



from user.models import User_Info

#from  operation.models import Topic_Comment
# Create your models here.











#外键
class  Create_Topic(models.Model):

    user=models.ForeignKey(User_Info,on_delete=models.CASCADE,verbose_name='发帖人')


    title=models.CharField(max_length=200,verbose_name='标题')

    content=models.TextField(verbose_name='编写内容')

    pub_time=models.DateTimeField(auto_now_add=True)

    read_nums = models.IntegerField(default=0, verbose_name=u"阅读次数")

    last_time=models.DateTimeField(auto_now=True)

    theme = (
        ('生物知识', '生物知识'),
        ('生物信息', '生物信息'),
        ('生活交流', '生活交流'),
        ('生信编程', '生信编程'),
        ('计算机学习', '计算机学习'),
        ('django学习', 'django学习'),
        # ('comments', '论坛公告'),
    )
    node = models.CharField(max_length=50, choices=theme, verbose_name='主题结点')
    top=models.CharField(max_length=5,verbose_name="是否置顶")
    notice=models.CharField(max_length=5,verbose_name='公告')
    class  Meta:
        verbose_name='发布主题'
        verbose_name_plural=verbose_name


    def  __str__(self):
        return  self.title

topic/forms.py
from  django  import   forms


class  PubTopic(forms.Form):
    title=forms.CharField(max_length=200,widget=forms.TextInput(attrs={"class":"textinput textInput form-control"}))

    theme = (
        ('生物知识', '生物知识'),
        ('生物信息', '生物信息'),
        ('生活交流', '生活交流'),
        ('生信编程', '生信编程'),
        ('计算机学习', '计算机学习'),
        ('django学习', 'django学习'),
        #('comments', '论坛公告'),
    )

    node=forms.ChoiceField(choices=theme,widget=forms.Select(attrs={"class":"select form-control"}))

    content_raw=forms.CharField(widget=forms.Textarea(attrs={"class":"pagedownwidget form-control wmd-input","cols":"40","rows":"10"}))




class  Comment_Forms(forms.Form):
    content_raw = forms.CharField(widget=forms.Textarea(attrs={"class": "pagedownwidget form-control wmd-input", "cols": "40", "rows": "10"}))

topic/views.py
from django.shortcuts import render,redirect,get_object_or_404
from  django.views.generic  import   View
from  django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from django.contrib.sessions.models import Session
from django.contrib.sessions.backends.db import SessionStore

from  user.models import User_Info
from  .models import Create_Topic
from  .forms import    PubTopic,Comment_Forms
from  operation.models import Topic_Comment


import  markdown




# Create your views here.



class  Index_View(View):
    '''
    查看所有主题标题
    '''
    def  get(self,request,page_id):
        topic_list=Create_Topic.objects.all().order_by('-pub_time')
        paginator=Paginator(topic_list,10)
        page_range=paginator.page_range
        page=request.GET.get(page_id)
        test=page_id
        #test=page
        try:
            topics=paginator.page(page_id)
            #test=topics
        except  PageNotAnInteger:
            topics=paginator.page(1)
            #test=topics
        except EmptyPage:
            topics=[]
                #paginator.page(paginator.num_pages)
        #处理侧边栏信息

        return  render(request,'topic/base.html',{'topics':topics,'page_id':(page_id+1)})




class  PubTopic_View(View):
    '''
    发布主题
    '''
    def  get(self,request,username):
        forms=PubTopic()
        return render(request, 'topic/create_topic.html',{'forms':forms})
    def  post(self,request,username):
        forms=PubTopic(request.POST)
        if  forms.is_valid():
            node=forms.cleaned_data["node"]
            title=forms.cleaned_data["title"]
            if  Create_Topic.objects.filter(title=title).exists():
                return  render(request,'topic/create_topic.html',{'forms':forms,'message':'该标题已经存在,请换一个标题'})
            content=forms.cleaned_data['content_raw']
            content=content.replace("<", " &lt;")
            content=content.replace(">", "&gt;")
            topic=Create_Topic()
            topic.user=User_Info.objects.get(username=username)
            topic.title=title
            topic.node=node
            topic.content=content
            topic.save()
            return  redirect(to='topic:index')
        else:
            return render(request,'topic/create_topic.html',{'forms':forms,'message':'输入的数据无法通过检查，请重新输入'})


class  Topic_Content_View(View):
    '''
    文章详细内容展示
    '''
    def  get(self,request,content_id):

        forms = Comment_Forms()
        topic_content=Create_Topic.objects.get(id=content_id)
        time=topic_content.pub_time
        title=topic_content.title
        name=topic_content.user.username
        node=topic_content.node
        content=markdown.markdown(
            topic_content.content,
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
            ]
        )

        comment=topic_content.topic_comment_set.all().order_by('-add_time')
        len_comment=len(comment)
        for  each_comment  in  comment:
            markdown_comment=markdown.markdown(
            each_comment.content,
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
            ]
        )
            each_comment.content=markdown_comment


        return render(request, 'topic/topic_content.html',{'content_topic':topic_content,"time": time, "title": title, "name": name, "content": content, "node": node,'forms':forms,'comment':comment,'len_comment':len_comment})




'''
    def  post(self,request,content_id):

        topic=Create_Topic.objects.get(id=content_id)
        login_user=User_Info.objects.get(username=request.user.username)
        forms=Comment_Forms(request.POST)
        if  forms.is_valid():
            comment_content=forms.cleaned_data["content_raw"]
            comment=Topic_Comment()
            comment.user=login_user
            comment.topic=topic
            comment.content=comment_content
            comment.save()

            return  render(request,'topic/topic_content.html',{'comment':comment,'forms':forms,'content_id':content_id})

'''







def  default_index(request):
    return  redirect(to='page/1')


'''
redirect  
可传递的参数： 
一个模型对象：这个模型的get_absolute_url() 会被调用。 
一个视图名称，可带参数，该视图会被反向生成。 
一个绝对路径或相对路径，用作反向定位。
'''


class  Theme1_View(View):
    def  get(self,request,theme_id):
        reservedict={
            '1':'生物知识',
            '2':'生物信息',
            '3':'生活交流',
            '4':'生信编程',
            '5':'计算机学习',
            '6':'django学习',
            '7':'论坛公告'
        }
        node_id=reservedict[str(theme_id)]
        theme1=Create_Topic.objects.filter(node=node_id)
        return render(request,'topic_base.html',{'theme':theme1,'theme_id':theme_id})

templates/topic/base.html
{% extends  'nav_base.html' %}
{% load  static %}
{% load  recent_reply %}
{% load theme_to_reply %}
{% load  all_node_theme %}

{% block  left_content %}
    <div class="panel panel-default">
        <div class="panel-body panel-subtitle">

            <span class="label label-success">按最新时间排序</span>

              <span class="pull-right ordering">
                  <strong>排序规则:</strong>
                <span>
                  <a href="/page/1">最新时间</a>
                </span>
                <span>
                  <a href="#">最新回复</a>
                </span>
              </span>

        </div>
        <!-- List group -->
        <ul class="list-group topic-list">
        {% if topics.top %}
            <li class="list-group-item topic-entry">
                    <div class="entry media">
                        <div class="media-left media-middle">
                            <a class="list-avatar-link" href="{% url 'topic:index' %}"><img class="user-avatar" src="http://www.gravatar.com/avatar/4e5750bb485db473fc5fcaac227b78e3?s=48&amp;d="></a>
                        </div>
                        <div class="media-body media-middle">
                            <a href="{% url 'topic:index' %}" class="entry-link">
                                {{ topic.title }}
                            </a>
                            <p class="entry-meta">

                                <span class="meta">
                                    <span class="label label-info meta-top">
                                        TOP
                                    </span>
                                </span>

                                <span class="meta">
                                    <a href="/n/1/">
                                        <span class="label label-default meta-node">
                                        General
                                        </span>
                                    </a>
                                </span>
                                    <span class="meta meta-username">
                                        <a href="/u/1/">
                                            eric
                                        </a>
                                    </span>
                                    <span class="meta meta-pub_date">
                                        {{ topic.pub_time }}
                                    </span>
                                    <span class="meta meta-last_replied hidden-xs">
                                        Last Replied: 4 日 之前
                                    </span>
                            </p>
                        </div>
                        <div class="media-right media-middle">
                            <span class="badge">{{ topic.title }}</span>
                        </div>
                    </div>
                </li>
        {% endif %}

{% for topic  in  topics %}
 <li class="list-group-item topic-entry">
                    <div class="entry media">
                        <div class="media-left media-middle">
                            <a class="list-avatar-link" href="{% url 'topic:index' %}"><img class="user-avatar" src="{% static  'image/3.jpg' %}"></a>
                        </div>
                        <div class="media-body media-middle">
                            <a href="{% url 'topic:topic_content'  content_id=topic.id %}" class="entry-link">
                                {{ topic.title }}
                            </a>
                            <p class="entry-meta">

                                <span class="meta">
                                    <a href="/theme/{% all_node_theme topic.node %}/">
                                        <span class="label label-default meta-node">
                                        {{ topic.node }}
                                        </span>
                                    </a>
                                </span>
                                    <span class="meta meta-username">
                                        <a href="{% url  'user:infoprofile' username1=topic.user.username %}">
                                            <strong>{{ topic.user.username }}</strong>
                                        </a>
                                    </span>
                                    <span class="meta meta-pub_date">
                                        <strong>{{ topic.pub_time }}</strong>
                                    </span>
                                    <span class="meta meta-last_replied hidden-xs">
                                        <strong> 最新回复人：{% recent_reply topic.title %}</strong>
                                    </span>
                            </p>
                        </div>
                        <div class="media-right media-middle">
                            <a href="{% url 'topic:topic_content'  content_id=topic.id %}" class="entry-link">
                           <span class="badge">{% theme_to_reply topic.title %}</span>
                        </div>
                    </div>
                </li>

            {% endfor %}
        </ul>
        <div class="panel-footer">

    <nav>

        <ul class="pagination">
                        <li><a href="/page/1/">1</a></li>

                        <li><a href="/page/2/">2</a></li>
            <li><a href="/page/3/">3</a></li>


                <li>
                    <a href="/page/{{ page_id }}/" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>

        </ul>
    </nav>

        </div>
    </div>


	    {% endblock %}

templates/topic/create_topic.html
{% extends  'nav_base.html' %}
{% load  static %}
{% block  left_content %}

    {% if  request.user.is_authenticated  %}

    <div class="panel panel-default">
        <div class="panel-body">
            <form method="post" action="{% url  'topic:create_topic'  username=request.user.username %}">


<form  method="post" >
    {% csrf_token %}
    <link href="{% static  'editor/demo.css' %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{% static 'editor/editor1.css' %}" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="{% static  'editor/Markdown.Converter.js' %}"></script>
<script type="text/javascript" src="{% static  'editor/Markdown.Converter1.js' %}"></script>
<script type="text/javascript" src="{% static  'editor/Markdown.Sanitizer.js' %}"></script>
<script type="text/javascript" src="{% static  'editor/Markdown.Editor.js' %}"></script>
<script type="text/javascript" src="{% static  'editor/Markdown.Extra.js' %}"></script>
<script type="text/javascript" src="{% static  'editor/pagedown_init.js' %}"></script>
    <div id="div_id_node" class="form-group"> <label for="id_node" class="control-label  requiredField">
        {% if  message %}
        <p>{{ message }}</p>
            {% endif %}
                主题<span class="asteriskField">*</span> </label> <div class="controls ">
                  {{ forms.node }}
</div> </div> <div id="div_id_title" class="form-group"> <label for="id_title" class="control-label  requiredField">
                标题<span class="asteriskField">*</span> </label> <div class="controls "> {{ forms.title }} </div> </div> <div id="div_id_content_raw" class="form-group"> <label for="id_content_raw" class="control-label  requiredField">
                内容<span class="asteriskField">*</span> </label> <div class="controls "> <div class="wmd-wrapper" id="id_content_raw-wmd-wrapper"> <div class="wmd-panel"> <div id="id_content_raw_wmd_button_bar"></div> {{ forms.content_raw }} </div> <p class="wmd-preview-title"><small>markdown输出浏览:</small></p> <div id="id_content_raw_wmd_preview" class="wmd-panel wmd-preview"></div> </div> </div> </div> <div class="form-group"> <div class="controls "> <input type="submit"
    name="submit"
    value="Submit"

        class="btn btn-primary"
        id="submit-id-submit"


    /> </div> </div> </form>

            </form>
        </div>
    </div>
{% else %}

    <div class="panel panel-default">
        <div class="panel-heading">参与评论</div>
        <div class="panel-body">


                    <div class="alert alert-warning" role="alert">



                            请 <a href="{% url  'user:login' %}">登录</a> 或者 <a href="{% url 'user:register' %}">注册一个新用户</a> 去回复

                    </div>


        </div>
    </div>
    {% endif %}
{% endblock %}

templates/topic/index1.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="zh_Hans" xml:lang="zh_Hans" />

  <head>
    <title>
      BioForum
      -
      A Forum powered by Django
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" type="text/css" media="screen" href="https://static.haoluobo.com/lbforum/lbforum/styles/v2ex/default.css"/>
  </head>

<body>

<div id="Top">
  <div id="TopMain">
    <p id="title"><a href="/">BioForum</a></p>
    <div id="Navigation">
      <ul>
          <li>
	<a href="/">论坛首页</a>
</li>
<li>
	<a href="#">博客</a>
</li>
          <li id="navregister"><a href="{% url 'user:register' %}">注册</a></li>
          <li id="navlogin"><a href="{% url 'user:login' %}">登录</a></li>
      </ul>
    </div>
<div id="Search">
      <form action="/recent/">
        <input type="text" class="search" maxlength="40" name="q" value="" id="q">
        <input type="submit" class="super normal button" value="Search" style="-moz-border-radius: 0px 5px 5px 0px; border: none;">
      </form>
    </div>
  </div>
</div>

{% block   content %}
{% endblock %}

      <div class="c">
      </div>
    </div>
  </div>

<div id="Bottom">
  <div id="BottomMain">
    <span class="fade">Copyright &copy; 2017 ~ 2018 <a href="https://www.lovexu.xyz">我爱小徐子</a></span>
    <div class="fr" style="float:right;color: #999999;">
      Powered by <strong><a href="https://www.djangoproject.com/">django</a></strong>
    </div>
  </div>
</div>

  </body>
</html>

templates/topic/info_profile.html
{% extends  'nav_base.html' %}
{% load  all_node_theme %}
{% load  theme_to_reply %}
{% load  recent_reply %}
{% block  left_content %}

<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-2 col-sm-1">
                <img class="user-avatar" src="http://www.gravatar.com/avatar/e7299b7998581a411f3189c4139ce032?s=48&amp;d=" alt=""/>
            </div>
            <div class="col-xs-9 col-sm-10">
                <p>{{ userinfo.username }}</p>
                <p>唯一标识符：{{ userinfo.id }}</p>
            </div>
        </div>
    </div>
</div>
    <div class="panel panel-default">
        <div class="panel-body panel-subtitle">
            <span class="label label-success">

                <font size="3" color="#1e90ff">    由【{{ userinfo.username }}】创造的主题</font>

            </span>
        </div>
        <!-- List group -->
        <ul class="list-group topic-list">

            {% for  each_user_theme in  user_theme %}

                <li class="list-group-item topic-entry">
                    <div class="entry media">
                        <div class="media-body media-middle">
                            <a href="{% url  'topic:topic_content'  content_id=each_user_theme.id %}" class="entry-link">
                               {{  each_user_theme.title  }}
                            </a>
                            <p class="entry-meta">
                                <a href="/theme/{% all_node_theme each_user_theme.node %}/">
                                        <span class="label label-default meta-node">
                                        {{ each_user_theme.node }}
                                        </span>
                                </a>
                                    <span class="meta meta-pub_date">

                                        <strong>发表时间:{{ each_user_theme.pub_time }}</strong>
                                    </span>
                                    <span class="meta meta-last_replied hidden-xs">
                                        <strong>最新回复人: {% recent_reply  each_user_theme.title %}</strong>
                                    </span>
                            </p>
                        </div>
                        <div class="media-right media-middle">
                            <span class="badge">{% theme_to_reply  each_user_theme.title %}</span>
                        </div>
                    </div>
                </li>
            {% endfor %}

            <li class="list-group-item">
                <!--a href="/u/279/topics/" class="text-success">More topics from this user</a-->
            </li>
        </ul>
    </div>

    <div class="panel panel-default">
        <!-- List group -->
        <ul class="list-group topic-list">

        </ul>
    </div>





{% endblock %}

templates/topic/info_reply.html
{% extends  'nav_base.html' %}
{% load  all_node_theme %}
{% load  theme_to_reply %}
{% load  recent_reply %}
{% block  left_content %}

<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-2 col-sm-1">
                <img class="user-avatar" src="http://www.gravatar.com/avatar/e7299b7998581a411f3189c4139ce032?s=48&amp;d=" alt=""/>
            </div>
            <div class="col-xs-9 col-sm-10">
                <p>{{ userinfo.username }}</p>
                <p>唯一标识符：{{ userinfo.id }}</p>
            </div>
        </div>
    </div>
</div>

    <div class="panel panel-default">
        <div class="panel-body panel-subtitle">
            <span class="label label-success">

                <font  size="3" color="#1e90ff">【{{ userinfo.username }}】发出的所有评论</font>

            </span>
        </div>
        <!-- List group -->
        <ul class="list-group topic-list">
            {% for  each_user_reply in  all_user_reply %}

                <li class="list-group-item reply-entry reply-entry-title">
                    评论的帖子：
                    <a href="{% url  'topic:topic_content' content_id=each_user_reply.topic.id %}">{{ each_user_reply.topic.title }}</a>
                    <span class="pull-right">{{ each_user_reply.add_time }}</span>
                </li>
                <li class="list-group-item reply-entry reply-entry-content">

                        {{ each_user_reply.content|safe }}
                    </p>
</p>
                </li>

            {% endfor %}



        </ul>
    </div>






    <div class="panel panel-default">
        <!-- List group -->
        <ul class="list-group topic-list">

        </ul>
    </div>





{% endblock %}

templates/topic/topic_content.html
{% extends 'nav_base.html' %}
{% load  static %}
{% block  left_content %}
<div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-body">
            <ol class="breadcrumb">
                <li><a href="/">主页</a></li>
                <li><a href="/n/1/">{{ node }}</a></li>
                <li class="active">{{ title }}</li>
            </ol>
            <h1 class="topic-title">{{ title }}</h1>
            <div class="topic-meta row">
                <div class="col-xs-2 col-sm-1">
                    <img class="user-avatar" src="{% static  'image/4.jpg' %}" alt=""/>
                </div>
                <div class="col-xs-9 col-sm-10">
                    <p class="text-muted">
                        <a href="/u/1/">{{ name }}</a>
                        <br/>
                        <span>发表于{{ time }} 主题：<a class="text-primary" href="/n/1/">{{ node }}</a>, </span>
                        <!--span>阅读次数  366</span-->
                    </p>
                </div>
            </div>

            <div class="topic-content">


{{ content|safe }}



</div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">

                共{{ len_comment }}条回复

        </div>
        <!-- List group -->
        <ul class="list-group reply-list">



{% for  each_comment  in  comment %}

<li class="list-group-item reply-item">
                    <div class="topic-meta row">
                        <div class="col-xs-2 col-sm-1">
                            <img class="user-avatar" src="{% static 'image/1.jpg' %}" alt="">
                        </div>
                        <div class="col-xs-9 col-sm-10">
                            <p class="text-muted">
                                <a href="/u/15/">{{ each_comment.user }}</a> <br>
                                <span>{{ each_comment.add_time }}</span>
                            </p>
                        </div>
                    </div>
                    <div class="reply-content">
                        <p>
                            </p><p>{{ each_comment.content|safe }}</p>

                        <p></p>
                    </div>
                    <p class="reply-link">
                        <a href="#" data-username="gladuo" class="reply-to">回复</a>
                    </p>

                </li>
{% endfor %}







        </ul>
        <div class="panel-footer">


        </div>
    </div>


     <div class="panel panel-default">
        <div class="panel-heading">留下一个评论</div>
        <div class="panel-body">


            {% if  request.user.is_authenticated %}
             <form action="{% url 'operation:comment_url'  content_id=content_topic.id %}" method="POST">

<form  method="post" >

    {% csrf_token %}
    <link href="{% static  'editor/demo.css' %}" type="text/css" media="all" rel="stylesheet" />



    <link href="{% static  'editor/editor1.css' %}" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="{% static  'editor/Markdown.Converter.js' %}"></script>
<script type="text/javascript" src="{% static  'editor/Markdown.Converter1.js' %}"></script>
<script type="text/javascript" src="{% static  'editor/Markdown.Sanitizer.js' %}"></script>
<script type="text/javascript" src="{% static   'editor/Markdown.Editor.js' %}"></script>
<script type="text/javascript" src="{% static  'editor/Markdown.Extra.js' %}"></script>
<script type="text/javascript" src="{% static  'editor/pagedown_init.js' %}"></script> <div id="div_id_content_raw" class="form-group"> <div class="controls "> <div class="wmd-wrapper" id="id_content_raw-wmd-wrapper"> <div class="wmd-panel"> <div id="id_content_raw_wmd_button_bar"></div> {{ forms.content_raw }} </div> <p class="wmd-preview-title"><small>Preview:</small></p> <div id="id_content_raw_wmd_preview" class="wmd-panel wmd-preview"></div> </div> </div> </div> <div class="form-group"> <div class="controls "> <input type="submit"
    name="submit"
    value="Submit"

        class="btn btn-primary"
        id="submit-id-submit"


    /> </div> </div> </form>

                    </form>

            {% else %}

<div class="alert alert-warning" role="alert">



                            请您<a href="{% url  'user:login' %}">登录</a> 或者 <a href="{% url  'user:register' %}">注册成为新用户</a> 进行回复

                    </div>
            {% endif %}















        </div>
    </div>


{% endblock %}